if ENV['FAST_PATH'] then
  FAST_PATH = ENV['FAST_PATH']
  if ENV['FAST_PATH_APP'] then
    import "#{FAST_PATH}/mobile/apps/android/Fastfile"
  else
    import "#{FAST_PATH}/mobile/sdks/android/Fastfile"
  end
else
  if ENV['SA_USE_DEV_FASTFILE'] then
    USER = `printf $USER`
    #Fetch sa-continous-integration path and trim any newlines and trailing white space
    dirtySALocalRepoDirectory = sh("find /users/#{USER} -name sa-continuous-integration -maxdepth 2 -type d | tr -d '\n'")
    saLocalRepoDirectory = "#{dirtySALocalRepoDirectory}".strip
    import "#{saLocalRepoDirectory}/mobile/sdks/android/Fastfile"
  else
    import_from_git(
      url: "https://github.com/superawesome-org/sa-ci-docker.git",
      branch: "main",
      path: "mobile/sdks/android/Fastfile",
    )
  end
end
